# Generated by Django 4.2.6 on 2023-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hard cover'), ('paperback', 'Paper back'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hardcopy', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('biography', 'Biography'), ('classic', 'Classic'), ('comic', 'Comic'), ('cookbook', 'Cookbook'), ('crime', 'Crime'), ('educational', 'Educational'), ('essay', 'Essay'), ('fantasy', 'Fantasy'), ('graphic novel', 'Graphic novel'), ('history', 'History'), ('historical fiction', 'Historical fiction'), ('horror', 'Horror'), ('memoir', 'Memoir'), ('mystery', 'Mystery'), ('poetry', 'Poetry'), ('romantic', 'Romantic'), ('self-development', 'Self-development'), ('science fiction', 'Science fiction'), ('thriller', 'Thriller')], default='classic', max_length=20),
        ),
    ]
