# Generated by Django 4.2.6 on 2023-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_name_book_title_alter_book_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('spanish', 'Spanish')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('ebook', 'E-Book'), ('audiobook', 'Audiobook')], default='hardcopy', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('biography', 'Biography'), ('classic', 'Classic'), ('comic', 'Comic'), ('cookbook', 'Cookbook'), ('crime', 'Crime'), ('educational', 'Educational'), ('essay', 'Essay'), ('fantasy', 'Fantasy'), ('graphic novel', 'Graphic novel'), ('history', 'History'), ('historical fiction', 'Historical fiction'), ('horror', 'Horror'), ('memoir', 'Memoir'), ('mystery', 'Mystery'), ('poetry', 'Poetry'), ('romantic', 'Romantic'), ('self-development', 'Self-development'), ('science fiction', 'Science fiction'), ('thriller', 'Thriller'), ('other', 'Other')], default='classic', max_length=20),
        ),
    ]
