# Generated by Django 4.2.6 on 2023-11-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_book_sale_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='book_name',
            new_name='book',
        ),
    ]
